[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 192, in checkDownload()] [ERROR] MI6_Prezzi2019110820191108.zip download failed
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 192, in checkDownload()] [ERROR] MI6_Prezzi2019110820191108.zip download failed
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 192, in checkDownload()] [ERROR] MI6_Prezzi2019110820191108.zip download failed
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 192, in checkDownload()] [ERROR] MI6_Prezzi2019110820191108.zip download failed
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 192, in checkDownload()] [ERROR] MI6_Prezzi2019110820191108.zip download failed
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 192, in checkDownload()] [ERROR] MI6_Prezzi2019110820191108.zip download failed
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 192, in checkDownload()] [ERROR] MI6_Prezzi2019110820191108.zip download failed
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 192, in checkDownload()] [ERROR] MI6_Prezzi2019110820191108.zip download failed
[gme.py, line 139, in getData()] [WARNING] Trying again...
[gme.py, line 191, in checkDownload()] [ERROR] MI3_LimitiTransito2019120120191231.zip download failed
[gme.py, line 138, in getData()] [WARNING] Trying again...
[gme.py, line 191, in checkDownload()] [ERROR] MI3_LimitiTransito2019120120191231.zip download failed
[gme.py, line 138, in getData()] [WARNING] Trying again...
[gme.py, line 191, in checkDownload()] [ERROR] MI3_LimitiTransito2019120120191231.zip download failed
[gme.py, line 138, in getData()] [WARNING] Trying again...
[gme.py, line 191, in checkDownload()] [ERROR] MI3_LimitiTransito2019120120191231.zip download failed
[gme.py, line 138, in getData()] [WARNING] Trying again...
[gme.py, line 191, in checkDownload()] [ERROR] MI3_LimitiTransito2019120120191231.zip download failed
[gme.py, line 138, in getData()] [WARNING] Trying again...
[gme.py, line 191, in checkDownload()] [ERROR] MI2_Prezzi2019110920191109.zip download failed
[gme.py, line 138, in getData()] [WARNING] Trying again...
[gme.py, line 191, in checkDownload()] [ERROR] MI2_Prezzi2019110920191109.zip download failed
[gme.py, line 138, in getData()] [WARNING] Trying again...
